name: 🚢 Deploy Workers

on:
  push:
    branches:
      - main

jobs:
  john:
    if: github.repository == 'One-Language/Website'
    runs-on: ubuntu-latest
    name: 🤓 😎 John
    steps:
      - uses: actions/checkout@v3
      - name: 🚀 Publish
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/john'
          command: deploy
